1. Create a list using the following list of average summer temperatures (in degrees Celsius) and name it 'templist':
30, 33, 27, 25

In [1]:
# Your Code Here
templist = [30,33,27,25]
print(templist)

2. Create an array using the following list of average summer temperatures (in degrees Celsius) and name it 'temparray':
30, 33, 27, 25

In [ ]:
# Your Code Here
import numpy as np



3. Convert templist and temparray to Farenheit. Which one was easier?

In [ ]:
# Your Code Here


4. Create an array using the following list of summer temperatures:
- 85, 77, 87, 93, 105 (NOTE: Numbers are in Farenheit)
- 31, 34, 28, (NOTE: Numbers are in Celsius)

Concatenate the first array with the second and print the result. The entire array should be in Fareinheit.

In [10]:
# Your Code Here

import numpy as np

farenheitTemps = np.array([85,77,87,93,105])
celsiusTemps = np.array([31,34,28])

cel_to_f = celsiusTemps*1.8+32

combined_temps = np.concatenate((farenheitTemps, celsiusTemps))
print(combined_temps)




[ 85  77  87  93 105  31  34  28]


5. Sort the above array from lowest to heighest temperature and print the result

In [15]:
# Your Code Here

print(np.sort(combined_temps))

x = np.sort(combined_temps)
print(x[::-1][0])

[ 28  31  34  77  85  87  93 105]
105


6. Calculate the mean, median, and standard deviation of temparray. Print the results.

In [ ]:
# Your Code Here



7. Create a 3x3 matrix with the following values: 
2, 4, 6
1, 3, 5
7, 9, 11

In [24]:
# Your Code Here
import numpy as np

matrix = np.mat([[2,4,6],[1,3,5],[7,9,11]])
print(matrix)
print("The shape of this matrix is... " , matrix.shape)

[[ 2  4  6]
 [ 1  3  5]
 [ 7  9 11]]
The shape of this matrix is...  (3, 3)


8. Create an array named 'evenNumbers' containing all even numbers from 2 to 20 (inclusive) using Numpy's arange method.

In [16]:
# Your Code Here
import numpy as np

evenNumbers = np.arange(2,21,2)
print(evenNumbers)

[ 2  4  6  8 10 12 14 16 18 20]


9. Reshape the 'evenNumbers' array into a 5x2 matrix and print the result.

In [18]:
# Your Code Here

new_even_numbers = evenNumbers.reshape(5,2)
print(new_even_numbers)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]
